#!/bin/bash
cd $1  # move to directory that needs setting up

test_dir=$(dirname "$0")
cp $test_dir/othello.txt .
STR="cs0330 shell 1 append test"
echo $STR > redirect.txt

# expected output
echo $STR > output
figlet -L -p < othello.txt >> output
